# build명령 예시: docker build -f ./buildfile/Dockerfile_python -t mergesrc --build-arg PROJECT_FOLDER=python --build-arg APPNAME=mergesrc.py .
# run 명령 예시: docker run --name mergesrc -it --rm -v .:/app mergesrc

# 파이썬 3.9 이미지를 베이스로 사용
FROM python:3.9

# Arguments
ARG PROJECT_FOLDER
ARG APPNAME
ENV APPNAME ${APPNAME}

# 작업 디렉토리 설정
WORKDIR /app

# 파이썬 프로그램 파일 복사
COPY ${PROJECT_FOLDER}/${APPNAME} ./python/${APPNAME}

# 컨테이너 실행 시 파이썬 프로그램 실행
CMD ["sh", "-c", "python ./python/${APPNAME}"]
